### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by FPS-86** [procon-plugin/vip-slot-manager#1]
Hi ! I have a mistake

```
[13:01:30 44] [VIP Slot Manager] ERROR: [SqlAutoDatabaseCleaner] SQL Error (Con): MySql.Data.MySqlClient.MySqlException (0x80004005): Truncated incorrect date value: '0000-00-00'
   в MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   в MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   в MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   в MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   в MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   в MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   в PRoConEvents.VipSlotManager.DatabaseCleaner()
[13:01:30 44] [VIP Slot Manager] [SqlAutoDatabaseCleaner] SQL Connection Error. Can not write in SQL
```

**Comment by AndreSpecker** [comment]
I have the same error, but the plugin is working normally

```
[09:14:02 52] [VIP Slot Manager] ERROR: [SqlAutoDatabaseCleaner] SQL Error (Con): MySql.Data.MySqlClient.MySqlException (0x80004005): Truncated incorrect date value: '2021-07-25 11:54:55'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at PRoConEvents.VipSlotManager.DatabaseCleaner()
[09:14:02 52] [VIP Slot Manager] [SqlAutoDatabaseCleaner] SQL Connection Error. Can not write in SQL
```
